version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: go-htmx-mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=newsdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/newsdb --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-htmx-mongo-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=newsdb
      - SERVER_PORT=8080
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
